### ISSUE TITLE
Upgrade pycromanager to 0.18.3

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#141]
For `1.0.0` we are planning to move `io` from `waveorder` to `recOrder`.

In [this `waveorder` PR](https://github.com/mehta-lab/waveorder/pull/79
), @ieivanov ran into a lazy-loading IO issue in his pycromanager reader that is solved in pycromanager 0.18.3. 

I'm tagging this here so that we:
- upgrade pycromanager for 1.0.0
-  remember to test the pycromanager reader when we upgrade pycromanager

**Comment by ziw-liu** [comment]
Is this resolved in [#183](https://github.com/mehta-lab/recOrder/pull/183)? If so we can remove this from the 1.0.0 milestone (as it will ship with 0.2.0) and close the issue.

**Comment by talonchandler** [comment]
Thanks for flagging @ziw-liu. I will be testing the pycromanager reader with Rachel tomorrow morning, so I'll close this when I've confirmed that the pycromanager reader is working for her. 

I'll change this issue to 0.2.0 so that I don't forget.

**Comment by ieivanov** [comment]
I just tested MM 090122 - it does not yet implement an important TriggerScopeMM bug fix, which was merged shortly after: https://github.com/micro-manager/mmCoreAndDevices/pull/238. It may be worth pushing the MM nightly build version by a couple of days later

**Comment by talonchandler** [comment]
Roger that...thanks for testing on the Triggerscope, Ivan. I'll bump to 2022-09-20 and test it before I merge this.
