### ISSUE TITLE
"Use cropped ROI" feature reported as not working with Oryx camera

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#143]
Yuming from the Elicieri group reported that the "Use cropped ROI" feature is not working with the Oryx camera. 

Any experience @Soorya19Pradeep @ieivanov? I can test early next week.

**Comment by ieivanov** [comment]
Spinnaker cameras used to have problems with cropping (unrelated to recOrder), which I fixed recently: https://github.com/micro-manager/mmCoreAndDevices/pull/208 If they are using an old device adapter, they can fetch this new version from a more recent MM install. Let me know if that doesn't fix the problem.

**Comment by talonchandler** [comment]
Thanks @ieivanov! I'll point Yuming to this improvement, and I'll close this when I hear back that it's fixed.

**Comment by talonchandler** [comment]
Yuming report similar issues when he tried with the latest device drivers (nightly build 2022_08_08). I tested the Oryx camera and confirmed that the `setROI` function bugs are in the MM device driver, not recOrder. 

I opened [an issue in mmCoreAndDevices](https://github.com/micro-manager/mmCoreAndDevices/issues/234), so I'm closing this.
