### ISSUE TITLE
Rename CLI options

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#147]
In #140 @ieivanov renamed the `ZarrConverter` constructor arguments from `input/output` to `input_dir/output_dir`. I think this is an improvement, and I think the CLI options should be renamed to match this choice. 

I also think all of the CLI options should be changed from `snake_case` to `kebab-case` to match common CLI conventions.

This change will break backwards compatibility, so it will be a 1.0.0 change.

**Comment by ieivanov** [comment]
`kebab-case`, that was a good laugh, thank you :)

**Comment by mattersoflight** [comment]
recOrder CLI will change substantially with release 0.3.0 (`recOrder convert` and `recOrder info` will become `iohub convert` and `iohub info`). I am not worried about this being a change in API.  I am assigning this to 0.3.0.
