### ISSUE TITLE
[BUG] "Load calibration" followed by "Capture Background" gives error

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#180]
"Load calibration" followed by "Capture Background" yields:
`Error: unsupported operand type(s) for *: 'NoneType' and 'float'`

**Comment by talonchandler** [comment]
It seems like the `lca{a/b}_{0,60,120}` attributes of `QLIPP_Calibration` are not being set correctly during "Load calibration".

Ziwen, would you mind helping out with this? I think you should be able to recreate this issue locally.

**Comment by ziw-liu** [comment]
Found these lines in `load_calibration`:

https://github.com/mehta-lab/recOrder/blob/00cf5ad0d733aad44067a8e65639f67abb446cd5/recOrder/plugin/workers/calibration_workers.py#L370-L372

It seems to me that the `return` line does not do anything here?

**Comment by talonchandler** [comment]
I *think* the `return` is used, but in a sneaky way by `self.worker.returned` here: 

https://github.com/mehta-lab/recOrder/blob/main/recOrder/plugin/widget/main_widget.py#L2460

It seems like the calibration must be returned somehow, or else the LCs wouldn't receive any of the data from the thread. 

This page was pretty helpful for me to understand how this section works:
https://napari.org/stable/guides/threading.html

"The [@thread_worker](https://napari.org/stable/api/napari.qt.threading.html#napari.qt.threading.thread_worker) decorator converts your function into one that returns a [WorkerBase](https://napari.org/stable/api/napari.qt.threading.WorkerBase.html#napari.qt.threading.WorkerBase) instance."
