### ISSUE TITLE
Native support for Apple Silicon

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#193]
**Problem**
`recOrder` does not currently support Apple Silicon (M1, M2, etc.) platforms natively due to the incompatibility between `pip` and PyQt5 (PyQt5 does not have a wheel for `arm_64` on PyPI). Native installation would be beneficial for both performance and potential GPU-accelerated processing/ML with a Metal backend.

**Proposed solution**
Closely track [napari's progress on supporting Qt6](https://github.com/napari/napari/issues/3880), since PyQt6/PySide6 have wheels available for the Apple Silicon platform on PyPI. And we can upgrade `recOrder` accordingly when napari makes the move. (They already have initial support merged into the main branch).
This may evolve into a broader set of [1.0.0](https://github.com/mehta-lab/recOrder/milestone/3) issues if napari starts supporting Qt 6 in a stable release soon enough.

**Alternatives**
- Offer a conda environment file that installs PyQt5 from `conda-forge`. This would require the removal of explicit dependency on `napari` in `setup.cfg`. #187

**Comment by ziw-liu** [comment]
napari 0.4.17 has added experimental support for Qt6. `pip install napari pyqt6` now works on macOS_arm64. 

The only blocking factor is now the `napari[all]` line in `recOrder`'s `setup.cfg`, which really is an alias for `napari pyqt5 scikit-image`. Changing to `napari` allows editable install of `recOrder` on Apple Silicon:

<img width="1260" alt="recOrder-napari_arm64" src="https://user-images.githubusercontent.com/67518483/202587161-b13242fd-745d-4f67-822e-dea330f3f35f.png">

The glitching in style sheet rendering is [a known issue](https://github.com/napari/napari/pull/3707#issuecomment-1152997251) for napari with Qt6.

**Comment by mattersoflight** [comment]
@ziw-liu I am trying to setup an environment for mantis project on my osx_arm64 laptop. I have been able to install all dependencies, including `nidaqmax`, `dexp`, `pyqt6`, `napari`, `pycromanager`. But, when I try `pip install -e <dir-to-recOrder>` in the main branch, pip still tries to build a pyqt5 wheel and fails. 

How do I bypass pyqt5 dependency when setting up recOrder? 

Here is the pip output.
```
Collecting PyQt5!=5.15.0,>=5.12.3
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... -
```

**Comment by ziw-liu** [comment]
As suggested in https://github.com/mehta-lab/recOrder/issues/193#issuecomment-1319382740, for the current `recOrder` you would need to manually delete this line:
https://github.com/mehta-lab/recOrder/blob/7e10ae59a1ed28cf28052b97404a2c0eba4369ff/setup.cfg#L47
before installing. And then install napari with Qt6:
```sh
pip install napari pyqt6
```
