### ISSUE TITLE
[BUG] "Capture background" fails when MM is in live mode

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#203]
All other acquisition buttons will turn off MM live mode before acquiring, but "Capture background" will error. You might try mimicking the other acquisition buttons (i.e. "Run Calibration")?

Thanks!

**Comment by ziw-liu** [comment]
I tested on Automaton and found that the shutter might stay closed if it's been closed and is in 'Live' mode, and I've started fixing it in #205. However I didn't get any error messages. @talonchandler Can you share the error you encountered?

**Comment by talonchandler** [comment]
I've attached the traceback from Hummingbird when I hit "Capture background" when MM is in live mode. FWIW I have a shutter configured on hummingbird, so these might be coupled issues. 
[bkg-while-live-traceback.txt](https://github.com/mehta-lab/recOrder/files/9679721/bkg-while-live-traceback.txt)

I received the same message from the `main` branch and the in-progress [`mm-live-capture-bg`](https://github.com/mehta-lab/recOrder/tree/mm-live-capture-bg) branch
