### ISSUE TITLE
[FEATURE] Save computed retardance and orientation images alongside backgrounds 

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#204]
`recOrder` shows the computed retardance and orientation images alongside the raw background images. @ieivanov suggested saving these computed images in the BG folder as well, and I agree that this would be nice. 

We'll need to check that this change doesn't accidentally break the `load_bg` functions. 

@ziw-liu if you have time and capacity this would be great.

**Comment by ziw-liu** [comment]
This is a nice convenience feature, but I'm not sure about its backwards compatibility. The `load_bg` function can be easily modified for this but earlier versions will not be able to read data generated by the later versions. Also, is it possible that some user has a custom script that assumes a certain structure of the background directory as we do with `load_bg`?

**Comment by talonchandler** [comment]
Very true, good point. Maybe these get saved to a different folder than the BG folder?

**Comment by ziw-liu** [comment]
> Maybe these get saved to a different folder than the BG folder?

Do you mean this?
```
data/
--------
   | BG/
   | BG_visual/
```

**Comment by ziw-liu** [comment]
> How about if you make a subfolder `BG/visuals` which would include the computed images

That might just work. I'll try it out.

**Comment by ziw-liu** [comment]
@talonchandler By 'state plots' do you mean the plots in #199? If so are how do they relate to background correction?
