### ISSUE TITLE
[BUG] Check that LF States are defined correctly for the given calibration mode

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#217]
I ran into a bug on Hummingbird where the, for example, the `State1`  channel definition contained both the `String sent to - ` property and the `Voltage (V) LC-A` and `Voltage (V) LC-B` properties. When a channel is set in MM, the order in which channel properties are applies may not be well defined.

I was using the MM-Voltage calibration mode, which calibrates only the `Voltage (V) LC-A` and `Voltage (V) LC-B` properties. When I acquired data, one of the states had intensity which was obviously wrong, i.e. uncalibrated, presumably resulting from setting the LC state by sending the `state1` string to the LC, rather than applying the calibrated voltages. Removing the  `String sent to - ` property from the channel definition fixed the problem.

`recOrder` should check for correct definition of the LF channels. When using MM-Retardance calibration mode, channels State0-5 should only have the `String sent to - ` MeadowlarkLC property. When using MM-Voltage calibration mode channels should have only the `Voltage (V) LC-A` and `Voltage (V) LC-B` properties. When using the DAC calibration mode, the MeadowlarkLC device adapter should not be loaded in MM (at least until we develop a device adapter that can handle both software and DAC control).

**Comment by ieivanov** [comment]
Is it true that we now only use the MM-Voltage control mode on the HB? I can replace the old config file with the new debugged file I created.

**Comment by talonchandler** [comment]
Great find! The undefined behavior you observed here is very likely related to #191. 

Following our chat, I will:
- add installation instructions for `MM-Voltage` mode. I will show how to install `MM-Voltage` mode by default and  I'll move the `MM-Retardance` instructions to an aside. I'll also warn users not to put both presets in the same group. 
-  check the MM config settings at calibration time and throw an error if the user's config settings don't match their requested calibration mode. 

I'll take you up on your offer to update the old config file on hummingbird. Thanks @ieivanov
