### ISSUE TITLE
[BUG] Loading from default config error

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#220]
**Reproduction**
In 'Offline' mode, click 'Acquisition/Reconstruction -> Reconstruction Settings -> General -> Load Default Config'

Error traceback:
```
TypeError                                 Traceback (most recent call last)
File ~/Projects/recOrder/recOrder/plugin/widget/main_widget.py:2446, in load_default_config(self=<recOrder.plugin.widget.main_widget.MainWidget object>)
   2444 self.worker.dimension_emitter.connect(self.handle_reconstruction_dim_update)
   2445 self.worker.store_emitter.connect(self.handle_reconstruction_store_update)
-> 2446 self.worker.started.connect(self._disable_buttons)
        self.worker = None
        self = <recOrder.plugin.widget.main_widget.MainWidget object at 0x18b6b8f70>
   2447 self.worker.finished.connect(self._enable_buttons)
   2448 self.worker.errored.connect(self._handle_acq_error)

File ~/Projects/recOrder/recOrder/plugin/widget/main_widget.py:1161, in _populate_from_config(self=<recOrder.plugin.widget.main_widget.MainWidget object>)
   1159 # Parse Processing name mismatch fields
   1160 wavelengths = self.config_reader.wavelength
-> 1161 if not isinstance(wavelengths, list):
        wavelengths = None
   1162     self.ui.le_recon_wavelength.setText(str(int(self.config_reader.wavelength)))
   1163 else:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

So it appears that the wavelength value is not populated correctly.

**Comment by ziw-liu** [comment]
@talonchandler @ieivanov Can you help explain why the wavelength in config files have to be integers?

**Comment by ziw-liu** [comment]
The wavelength is set to `None` in the hard-coded `ConfigReader` defaults:
https://github.com/mehta-lab/recOrder/blob/0b3f4db6532fffd40aef74517a12e71f8284987f/recOrder/io/config_reader.py#L20-L26

But Expected in `MainWidget`:
https://github.com/mehta-lab/recOrder/blob/0b3f4db6532fffd40aef74517a12e71f8284987f/recOrder/plugin/widget/main_widget.py#L1159-L1167

**Comment by ziw-liu** [comment]
There's a 'double default' scenario here, as the default values that pops up with the GUI components (related: #216) does not agree with the defaults in `ConfigReader`. 

I would think that at least one set of them has to go to improve maintainability,. And ideally both are replaced with a separate default/example config file that the user would load just as they would with their own config files. Or we can reuse the existing configs for `pytest`.

@talonchandler @ieivanov What are your thoughts?

**Comment by talonchandler** [comment]
No need for wavelength to be an `int`. 

I think your idea to have default parameters loaded from a file makes a lot of sense. 

I'm also fine with choosing one or the other set of defaults for now. I marked my `main_widget.py` L127 as weird, so maybe it makes the most sense to undo that?

**Comment by talonchandler** [comment]
I'm also very tempted to do away with the "Load default parameters" button. 

Can we get away with populating all of the fields by default at startup?

**Comment by ziw-liu** [comment]
The problem here is that the the 'Load Default Parameters' button loads a very different set of values compared to GUI startup. Either way we would need to decide on a list of the desired 'default values', but then this essentially means that we already have a config file (just click 'Save Config to File')
