### ISSUE TITLE
[BUG] Illumination is shuttered during background correction

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#237]
Illumination is shuttered between channels during background correction, which can cause problems if the camera and shutter are not well coordinated. It will be better is the light is turn on at the beginning of collecting background images, left on between channels, and turn off at the end, like we do during data acquisition.

**Comment by ziw-liu** [comment]
The current implementation [uses MM's snap image API](https://github.com/mehta-lab/recOrder/blob/dc15b8a5e246deaa030b05ea0ab8a0e6523e1c45/recOrder/io/core_functions.py#L56) to acquire background, while data acquisition uses MDA. I don't know if our current workflow involving turning off/on Live Mode can be reimplemented with only MM Core calls. Or do you think we should use MDA for background?

**Comment by ieivanov** [comment]
Ah, I see. In that case, we can disable autoshutter and turn on the illumination at the beginning of BG correction. After a few snaps, we can reset the illumination and autoshutter to their previous state (e.g. leave lights on if that's how we found them)

**Comment by talonchandler** [comment]
I agree @ieivanov. I think we should start controlling the shutter from recOrder's background acquisition.  

Re background capture in 1.0.0 --- I've opened a separate issue #240.

**Comment by ziw-liu** [comment]
> we can disable autoshutter and turn on the illumination at the beginning of BG correction

I tried this and it seems like MM's 'Snap' button will still turn off/on the light (on Automaton). Also I think this is what the current implementation is trying to do:
https://github.com/mehta-lab/recOrder/blob/dc15b8a5e246deaa030b05ea0ab8a0e6523e1c45/recOrder/calib/Calibration.py#L1150-L1152

@ieivanov Any idea about how to work around this?

**Comment by ieivanov** [comment]
Hm, the code does seem to be written to do the right thing. It's strange that the shutters still close. I'll look at this in more detail on automaton.
