### ISSUE TITLE
On startup, plugin opens "Acquisition / Reconstruction" tab instead of "LC Calibration" tab

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#254]
Annoyingly, Qt Creator sets the startup tab focus to the last tab you were editing when you save the .ui file, so when I edit the .ui file I sometimes accidentally change the tab focus. 

The current behavior is an example of this problem: on startup the plugin opens to the "Acquisition / Reconstruction" tab instead of the expected "LC Calibration" tab.

@ziw-liu would you mind adding a couple lines to the `main_widget` constructor to fix the tab focus?

**Comment by ziw-liu** [comment]
Problematic line:
https://github.com/mehta-lab/recOrder/blob/ecca6ffc53752c45e0eaf03fe2a9621cc2da0faa/recOrder/plugin/gui.py#L1128

Changing From `(1)` to `(0)` solves the issue.
@talonchandler Do we want to modify it in `gui.UI_Form` or override in `main_widget.MainWidget`?
