### ISSUE TITLE
Overlay is not generated for 3D "Retardance + Orientation" reconstructions

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#263]
Acquiring "Retardance + Orientation" in 2D will result in an "Overlay" layer, but in 3D mode not overlay is generated. Can we use the same overlay settings and generate a 3D overlay by default?

**Comment by ziw-liu** [comment]
Currently the overlay is generated in the main widget thread. Performance might be an issue if we want to generate overlay for a large 3D volume in the same way.

**Comment by talonchandler** [comment]
Thanks for flagging this @ziw-liu. 

I just glanced through the `ret_ori_overlay` function, and I don't expect any of the operations to be extremely time consuming. Let's test a quick fix and think about optimizations or a separate thread if it's annoyingly slow.
