### ISSUE TITLE
Migrating IO module from `waveorder`

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#272]
Migrating [`waveorder.io`](https://github.com/mehta-lab/waveorder/blob/5f60f0ad27e05596a6f6cb09ef2310f6bc00f236/waveorder/io) to the `recOrder` package makes sense in that `recOrder` should be the user interface that works with files and experiment pipelines, and `waveorder`should be a computational library whose inputs and outputs are data objects (e.g. NumPy arrays).

While the `io` module is reasonably isolated from the rest of `waveorder`, the migration cannot be simply copy-pasting the files if we want to preserve the Git history. 

One potential way to do this:
1. Split `waveorder.io` into its own repo with [`git filter-repo`](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository) or [`git subtree split`](https://git.kernel.org/pub/scm/git/git.git/plain/contrib/subtree/git-subtree.txt);
2. Merge the new repo into `recOrder` with [Git subtree merge](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges);
3. Delete the intermediate repository.

Alternatively, we can keep the `io` module in the separate repo and include it as a [submodule](https://git-scm.com/docs/gitsubmodules). Or we can migrate it to [iohub](https://github.com/czbiohub/iohub) and depend on that instead.

@talonchandler @mattersoflight Any suggestions?

**Comment by mattersoflight** [comment]
Thanks for opening this issue @ziw-liu and proposing some solutions.

`iohub` will need to be developed further and set up properly with GitHub actions, documentation, and package management before it is public.  As a step towards that, moving the current `io` module to its own repo makes sense. Consequently, including the io repo in recOrder as a submodule makes sense. The submodule-approach can allow us to package the io repo as a submodule with not just recOder, but also with microDL. [Example 3 in this guide](https://oak-tree.tech/blog/python-packaging-primer) suggests this is quite doable, but the devil may be in the details. 

@jennyfolkesson , @talonchandler what are your inputs on the above packaging strategy? 
cc: @Christianfoley.

**Comment by talonchandler** [comment]
Thanks @ziw-liu...I don't have a strong preference. If we are considering moving `io` to a submodule of `recOrder` I would like to make sure we agree on a plan for:

- **PyPI packaging**: will we keep the same packaging structure: `recOrder` and `waveorder`? Or will the submodule be packaged by itself?
- **dependencies**: if we move `io` will `waveorder` need to depend on `recOrder`? Maybe this is fine?
- **testing**: will we test `waveorder` against synthetic data only? Or will we depend on `io` (through `recOrder`) and test on real data?

**Comment by ziw-liu** [comment]
> PyPI packaging: will we keep the same packaging structure: recOrder and waveorder? Or will the submodule be packaged by itself?

I was assuming that we keep the two existing packages unless there's any reason not to.

> dependencies: if we move io will waveorder need to depend on recOrder? Maybe this is fine?

Circular dependency will be troublesome. I think only having `recOrder` depend on `waveorder` is the cleanest approach here.

> testing: will we test waveorder against synthetic data only? Or will we depend on io (through recOrder) and test on real data?

We can use pickled NumPy arrays to avoid extra IO dependencies during tests, or make the test scripts do extra work to load from real datasets.

**Comment by jennyfolkesson** [comment]
I'm not sure I understand correctly... the IO currently existing in waveorder will be moved to its own repo, and then waveorder, recorder and microdl import will it from that IO repo? Then will the same IO be incorporated into iohub, so this is a step towards that goal?

If the end goal is to make a pypi package, I'd prefer, if possible, to skip the submodule step and just make the IO its own small pypi package which can be pip installed, because that seems simpler to me. But if there's someone who prefers to make the IO a submodule and import that to the other repos, I'll watch what they're doing and duplicate the steps for microdl. Or are there benefits of a submodule that I'm missing?

**Comment by mattersoflight** [comment]
@jennyfolkesson I agree that moving io module to its own repository and a separate package on which microDL, recOrder, waveOrder depend makes a lot of sense. In fact, we can move the updated `io` to `czbiohub/iohub`. I believe the current io module in waveOrder and code in `iohub`  have very manageable diffs. @ziw-liu and @talonchandler please check and let us know what you find.

**Comment by ziw-liu** [comment]
The diff between `waveorder.io` and `iohub` is manageable. However again we do not have a clean way to merge `waveorder.io` into `iohub` while preserving the Git history, since the [initialization](https://github.com/czbiohub/iohub/commit/38d87f8fc5931bb3295d6da6ce6f1ae4bb584339) of `iohub` was just copy-pasting code from `waveorder.io`. In this case I would imagine a path similar to:

1. Split out `waveorder.io` as its own Git repo;
2. Rearrange the directory layout to resemble that of `iohub` on a branch;
3. Set `iohub` as an `origin` for the new repo;
4. Git pull origin (from `iohub`) so that the mainstream for the new repo becomes `HEAD` of `czbiohub/iohub:main`.
5. Merge the transformed branch into the new `main`
6. PR to `czbiohub/iohub`.
7. Package the new `iohub`.

Again suggestions are welcome! And we may want to talk to @ AhmetCanSolak when he gets back.

**Comment by mattersoflight** [comment]
We decided to deprecate current `iohub` (which was developed only for 2 weeks) and move the io module to seed the new `iohub`. We also decided to maintain PTI reader in the iohub. We'll also develop reader methods for other automation pipelines (such as opencell).

**Comment by mattersoflight** [comment]
This issue is now copied to https://github.com/czbiohub/iohub/blob/main/docs/transferred_issues using gh2md package. We will continue the discussion there. Closing here.
