### ISSUE TITLE
incomplete metadata with multiprocessing script

### ISSUE THREAD

**Issue by JohannaRahm** [mehta-lab/recOrder#278]
The metadata files are incomplete after reconstructing and deconvolving a zarr store with the [multiprocessing script](https://github.com/mehta-lab/waveorder/blob/waveorder_scripts/examples/multiProcessing/Phase3D_fluor_deconv_waveorder_all_channels.py), perhaps due to multi processing.

In the robust virtual staining analysis pipeline, the reconstructed zarr stores with 336 positions is converted to single page tif, as this is the current microDL input format. The script iterates over `reader.reader.position_map`. However, only the last 14 positions are captured in `reader.reader.position_map` and `reader.reader.hcs_meta`. The conversion script has a workaround for now, which extracts the position list from the zarr folder structure.

Here are the paths to check it out:
- Convertion script: `/hpc/projects/comp_micro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_single_page/keyerror/hcszarr2single_tif_2022_03_15_keyerror.py`
- - Convertion script wih workaround: `/hpc/projects/comp_micro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_single_page/keyerror/hcszarr2single_tif_2022_03_15_keyerror_workaround.py`
- Zarr store: `/hpc/projects/comp_micro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_zarr/all_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50.zarr/`
- Single page tif directory: `/hpc/projects/comp_micro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_single_page/ll_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50_keyerror14/`

The command `reader.reader.hcs_meta` within the conversion file gives the following output
`pp.pprint(reader.reader.hcs_meta)`
Output:
```
{   'plate': {   'acquisitions': [   {   'id': 1,
                                         'maximumfieldcount': 1,
                                         'name': 'Dataset',
                                         'starttime': 0}],
                 'columns': [   {'name': 'Col_322'},
                                {'name': 'Col_323'},
                                {'name': 'Col_324'},
                                {'name': 'Col_325'},
                                {'name': 'Col_326'},
                                {'name': 'Col_327'},
                                {'name': 'Col_328'},
                                {'name': 'Col_329'},
                                {'name': 'Col_330'},
                                {'name': 'Col_331'},
                                {'name': 'Col_332'},
                                {'name': 'Col_333'},
                                {'name': 'Col_334'},
                                {'name': 'Col_335'}],
                 'field_count': 1,
                 'name': 'll_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50',
                 'rows': [{'name': 'Row_0'}],
                 'version': '0.1',
                 'wells': [   {'path': 'Row_0/Col_322'},
                              {'path': 'Row_0/Col_323'},
                              {'path': 'Row_0/Col_324'},
                              {'path': 'Row_0/Col_325'},
                              {'path': 'Row_0/Col_326'},
                              {'path': 'Row_0/Col_327'},
                              {'path': 'Row_0/Col_328'},
                              {'path': 'Row_0/Col_329'},
                              {'path': 'Row_0/Col_330'},
                              {'path': 'Row_0/Col_331'},
                              {'path': 'Row_0/Col_332'},
                              {'path': 'Row_0/Col_333'},
                              {'path': 'Row_0/Col_334'},
                              {'path': 'Row_0/Col_335'}]},
    'well': [   {'images': [{'path': '21-Pos002_000'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos003_000'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos003_001'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos002_001'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos001_001'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos000_001'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos000_002'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos001_002'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos002_002'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos003_002'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos003_003'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos002_003'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos001_003'}], 'version': '0.1'},
                {'images': [{'path': '21-Pos000_003'}], 'version': '0.1'}]}
```

@talonchandler rightfully pointed out that the length of meta data in alignment with the number of cores requested for the job: '24 cores --> 336/24 = 14 which leads me to believe that the last process to finish writes the zarr store info'

Another minor thing is that the first character of the zarr store name is missing in `reader.reader.hcs_meta`. Instead of `'name': 'all_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50'` it says `'name': 'll_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50'`

**Comment by talonchandler** [comment]
This issue reemerged when @Soorya19Pradeep tried to open a few of the datasets @JohannaRahm processed with variants of the [multiprocessing scripts](https://github.com/mehta-lab/waveorder/tree/main/examples/multiProcessing). 

All of the `zarr` files in this folder (and all other files that used my multiprocessing scripts) suffer from the issue:
`/hpc/projects/compmicro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_zarr/`

If you run `recorder info` you'll see 14 positions, when in reality the stores contain 336 positions and the metadata is incorrect. 

I can fix the problem manually by adding entries to the `.zarr/.zattrs` files. See `all_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50.zarr` with the `backup_zattrs` and the improved `.zattrs` file that picks up 5 new positions and appears to have 19 positions instead of 14. 

@ziw-liu what do you think is the best strategy to handle this? Write a `fix-metadata` script that runs on these ~1 TB zarr stores? I admit that I caused this problem since I wrote the multiprocessing script, but the multiprocessing is/was enabling and I still don't know a better way to handle this metadata. Maybe a `fix-metadata` routine is necessary for `iohub` anyway if we hope to write to `ome-zarr` stores in parallel?

From @Soorya19Pradeep I understand that this issue may become a blocker within about a week?

**Comment by Soorya19Pradeep** [comment]
Thank you for remerging the issue @talonchandler! I want to read the zarr files @JohannaRahm has created to train the new models in pytorch. It will be great if I can start using the zarrs Johanna created as early as possible.

**Comment by ziw-liu** [comment]
> Write a `fix-metadata` script that runs on these ~1 TB zarr stores?

For existing dataset I think this might the quickest way to unblock analysis. If the only need is to add metadata then the array data size shouldn't be that concerning as they are in separate files. Another thing we can do is to patch the legacy reader with a 'greedy' mode.

> Maybe a `fix-metadata` routine is necessary for `iohub` anyway if we hope to write to `ome-zarr` stores in parallel?

Not quite necessary. If empty images are created before parallelized writing, the current iohub should write complete datasets with metadata. I think @edyoshikun may have tried?

**Comment by edyoshikun** [comment]
Currently, you can initialize an empty array with specific data shape `dchunks` and chunks, typically chunk in YX, `zchunks` like this: 

```python
    # Initialize the empty zarr store once
    with open_ome_zarr(
        store_path,
        layout="hcs",
        mode="w-",
        channel_names=["Retardance", "Orientation", "BF - computed", "DoP", "GFP_macs"],
    ) as dataset:
        # Make the positions
        for i in tqdm(range(reader.get_num_positions())):
            pos = dataset.create_position("position", str(i), "0")
            # this is a 'hack' to create placeholder metadata
            # future iohub should expose a public API for emtpy images
            pos._create_image_meta("0")
            arr = pos.zgroup.zeros(
                "0",
                shape=dchunks,
                chunks=zchunks,
                dtype=np.float32,
                **pos._storage_options
            )
        dataset.print_tree()
```

Which you can do stuff like [this](https://github.com/czbiohub/compmicro-sandbox/blob/master/zebrafishInfection/ed/optimize_bire.py)  and use multiprocessing with a `mp.Pool()` and parse through the array to fill it in with the data. 

This produces datasets like this one `/hpc/projects/comp_micro/projects/zebrafish-infection/2023_02_23_isg15_gfp_mpeg_tdtom_infected_ctrl_fish_day_8/bire_fluor_selected_pos03111223.zarr` and if use 
```python
reader = ImageReader(store_path)
reader.reader.hcs_meta
```
the output is the following:
```
{'plate': {'acquisitions': [{'id': 0}],
  'columns': [{'name': '26'},
   {'name': '27'},
   {'name': '12'},
   {'name': '13'},
   {'name': '10'},
   {'name': '11'}],
  'rows': [{'name': 'position'}],
  'version': '0.4',
  'wells': [{'columnIndex': 0, 'path': 'position[/26](https://vscode-remote+ssh-002dremote-002bcpu-002da-002d1.vscode-resource.vscode-cdn.net/26)', 'rowIndex': 0},
   {'columnIndex': 0, 'path': 'position[/27](https://vscode-remote+ssh-002dremote-002bcpu-002da-002d1.vscode-resource.vscode-cdn.net/27)', 'rowIndex': 1},
   {'columnIndex': 1, 'path': 'position[/12](https://vscode-remote+ssh-002dremote-002bcpu-002da-002d1.vscode-resource.vscode-cdn.net/12)', 'rowIndex': 1},
   {'columnIndex': 2, 'path': 'position[/13](https://vscode-remote+ssh-002dremote-002bcpu-002da-002d1.vscode-resource.vscode-cdn.net/13)', 'rowIndex': 1},
   {'columnIndex': 3, 'path': 'position[/10](https://vscode-remote+ssh-002dremote-002bcpu-002da-002d1.vscode-resource.vscode-cdn.net/10)', 'rowIndex': 1},
   {'columnIndex': 4, 'path': 'position[/11](https://vscode-remote+ssh-002dremote-002bcpu-002da-002d1.vscode-resource.vscode-cdn.net/11)', 'rowIndex': 1}]},
 'well': [{'images': [{'acquisition': 0, 'path': '0'}]},
  {'images': [{'acquisition': 0, 'path': '0'}]},
  {'images': [{'acquisition': 0, 'path': '0'}]},
  {'images': [{'acquisition': 0, 'path': '0'}]},
  {'images': [{'acquisition': 0, 'path': '0'}]},
  {'images': [{'acquisition': 0, 'path': '0'}]}]}
```
I am not sure if there is extra metadata that is needed? I don't write any extra along the way but it's probably 1-2 lines to add some to the `.zattrs` for each iteration during the MP.

**Comment by talonchandler** [comment]
Sounds good...I'm glad to hear that this will be solved by `iohub`. I'll write a quick script that fixes this---I've reassigned the issue to myself.

**Comment by Soorya19Pradeep** [comment]
Thanks to @talonchandler for figuring out an easy way to resolve this issue. We were able to copy the .zattrs file from the zarr store in raw data folder,
`/hpc/projects/CompMicro/rawdata/hummingbird/Janie/2022_03_15_orgs_nuc_mem_63x_04NA/all_21_3.zarr/.zattrs`
to the zarr stores created by multiprocessing, for instance, 
`/hpc/projects/CompMicro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_zarr/all_pos_Phase5e-4_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50.zarr/.zattrs`.
We have tested the dataset to check the metadata reads as expected (reads right number of positions, channel names, etc.) and it worked!

**Comment by talonchandler** [comment]
Thanks for posting @Soorya19Pradeep. 

This solution is a kludge, but we have a relatively small number of datasets to fix so it's workable. 

Going forward, we'll use `iohub` for all multiprocessing, so that metadata is written correctly. 

Closing.
