### ISSUE TITLE
Startup Tab

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#281]
When launching recOrder, the GUI defaults to the `Acquisition / Reconstruction` tab. It would be nice if it starts up at the `LC Calibration` tab.

**Comment by talonchandler** [comment]
Are you on the `main` branch? I think @ziw-liu fixed this in https://github.com/mehta-lab/recOrder/issues/254.

**Comment by ieivanov** [comment]
Aha - I installed the pypi version, probably that's not on there yet. Closing this
