### ISSUE TITLE
`pycromanager==0.19.2` depends on `numpy < 1.24.0`

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#300]
Yesterday's `numpy` 1.24.0 release deprecates `np.bool` which `pycromanager` depends on, which is breaking (fresh installations of) `recOrder` including our tests. 

I think we can:
1. Pin to `numpy==1.23.0` and/or
2. Wait for the next release of pycromanager that's compatible with `numpy==1.24.0` (see [this PR](https://github.com/micro-manager/pycro-manager/pull/475) I just opened) and upgrade our pycromanager dependency. 

What do you think @ziw-liu? I'm leaning towards 1 now, then 2 later.

**Comment by ziw-liu** [comment]
Thanks for the PR to upstream!
It makes sense to pin NumPy before PM's next release with the fix.

**Comment by ziw-liu** [comment]
https://github.com/micro-manager/pycro-manager/pull/475 has been merged. However, pycro-manager with this new patch won't be installed with recorder since we have pinned its version:

https://github.com/mehta-lab/recOrder/blob/655a7643f0b9cba3dc51ccb932cf3abc8db38037/setup.cfg#L41

@talonchandler @ieivanov What should we do to confidently bump PM dependency to [latest](https://github.com/micro-manager/pycro-manager/blob/main/pycromanager/_version.py)?

**Comment by talonchandler** [comment]
I think manually testing the MM connection and acquisitions on hummingbird will be enough to upgrade the PM dependency confidently. We might need to upgrade MM as well, but I don't think we'll know until we test. 

I'm not in any rush to upgrade. I think it can wait until after 0.3.0.

**Comment by talonchandler** [comment]
@ziw-liu I just realized that this issue affects new installations of `recOrder==0.2.0`. Would you mind releasing 0.2.1 with `numpy==0.23.5`? 

In the meantime, an easy workaround is `pip install recOrder-napari` followed by `pip install numpy==0.23.5`.

**Comment by ieivanov** [comment]
Now that we have automated testing, pycromanager should be a lot more reliable. We can more confidently upgrade and add tests for features we depend on

**Comment by ziw-liu** [comment]
> @ziw-liu I just realized that this issue affects new installations of `recOrder==0.2.0`. Would you mind releasing a patched version `0.2.1` with pinned `numpy==0.23.5`?

Just to be clear, should 0.2.1 be [0.2.0](https://github.com/mehta-lab/recOrder/releases/tag/0.2.0) with only [the NumPy version patch](https://github.com/mehta-lab/recOrder/commit/655a7643f0b9cba3dc51ccb932cf3abc8db38037), not any other additional commits?

**Comment by talonchandler** [comment]
👍 that’s perfect…just the pinned numpy version on top of 0.2.0. If you’re keen it might be worth testing a local install before releasing, but I have tested a by-hand numpy pin on two installations, so I’m quite confident it’ll be fine.

**Comment by ieivanov** [comment]
Heads up, as an added complication, `dexp` currently requires `numpy < 1.22`
