### ISSUE TITLE
Patch release 0.2.1

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#303]
> @ziw-liu I just realized that this issue affects new installations of `recOrder==0.2.0`. Would you mind releasing a patched version `0.2.1` with pinned `numpy==0.23.5`?

Just to be clear, should 0.2.1 be [0.2.0](https://github.com/mehta-lab/recOrder/releases/tag/0.2.0) with only [the NumPy version patch](https://github.com/mehta-lab/recOrder/commit/655a7643f0b9cba3dc51ccb932cf3abc8db38037), not any other additional commits?

_Originally posted by @ziw-liu in https://github.com/mehta-lab/recOrder/issues/300#issuecomment-1379303699_

**Comment by ziw-liu** [comment]
Opening a separate issue to track the 0.2.1 release.

**Comment by ziw-liu** [comment]
Candidate branch at https://github.com/mehta-lab/recOrder/tree/patch/0.2.x

**Comment by ziw-liu** [comment]
We also need https://github.com/mehta-lab/recOrder/pull/302/commits/37cadc762a04db154c8a791868df7165b182a5cc for CI. Should not affecting any user-facing functionality though.

**Comment by ziw-liu** [comment]
CI now passes: https://github.com/mehta-lab/recOrder/actions/runs/3904743819/jobs/6671049630

**Comment by ziw-liu** [comment]
Briefly tested `0.2.1rc0` on the Automaton. Releasing `0.2.1`.

**Comment by talonchandler** [comment]
Thanks for handling this @ziw-liu! I just downloaded from PyPI and confirmed that everything's working as expected on my local (MM demo-cam) installation.
