### ISSUE TITLE
Keep a maintenance branch for each minor version

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#304]
While working on #303 I noticed that there is not a branch to open a PR against, since we always released from `main`. Releasing a stable version without a PR seemed 'dirty', and can be avoided if we kept a maintenance branch for each minor version like [NumPy does](https://github.com/numpy/numpy/branches). I named the #303 branch `patch/0.2.x`, and we can either keep using this format or use another one like `bug-fixes/major.minor.x` or `maintenance/major.minor.x` instead.

**Comment by talonchandler** [comment]
Great idea. I don't have a major preference for the naming---`/patch/0.2.x` makes sense to me.

**Comment by mattersoflight** [comment]
Good idea. I checked if it is possible to branch off a tag and that works as needed. I vote for `maintenance/major.minor.x`. 
`git checkout -b patch/0.2.2 0.2.1`

**Comment by ziw-liu** [comment]
> I checked if it is possible to branch off a tag and that works as needed.

Yes, it should be possible to create a branch off of any commit, including tagged commits, but (I think) only branches can be valid merging targets (because tags are associated with a commit so it cannot be mutated).

**Comment by talonchandler** [comment]
@ziw-liu what needs to happen for this to close? Is this for immediately following the 0.3.0 release?

**Comment by ziw-liu** [comment]
> @ziw-liu what needs to happen for this to close? Is this for immediately following the 0.3.0 release?

I labelled this issue as `meta` since it's about making a decision about repo management. As soon as we all agree that we will (or will not) adopt the strategy, it can be closed.
