### ISSUE TITLE
Distribute MLO device drivers via MM nightly builds

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#311]
@ieivanov is leading an effort to distribute the MLO device driver's via MM nightly builds with progress here:
https://github.com/mehta-lab/mmCoreAndDevices/milestone/1

When the MLO device driver merges, on the `recOrder` side we'll need to:

- [x] Update `LC_DEVICE_NAME` (see https://github.com/mehta-lab/mmCoreAndDevices/issues/3)
- [x] Test the installation (from scratch and in voltage, retardance, and DAC modes) 
- [x] Update the docs to remove mention of these devices drivers
- [ ] Release `recOrder` ~0.3.0~ 0.4.0 without any device drivers

**Comment by talonchandler** [comment]
@ziw-liu @mattersoflight should we consider moving this to 1.0.0? 

If we want this issue solved in 0.3.0 and released by the end of the month, then we'll need to support @ieivanov to get the device drivers merged.

**Comment by ziw-liu** [comment]
> should we consider moving this to 1.0.0?

I'm fine with delaying this feature. If there's immediate need from users we can consider shipping an patch too.

**Comment by mattersoflight** [comment]
Ivan and I just chatted. If the new device adapter is ready (modulo the work on mantis) by the time we release 0.3.0, we will include it. Otherwise, we can create another minor release before undertaking the refactor for recOrder 1.0.0.

**Comment by talonchandler** [comment]
We are now successfully distributing `mmgr_dal_MeadowlarkLC.dll` via MM nightly builds, but we are still planning to distribute the usb driver via `recOrder`'s github release page pending permission from Meadowlark.

The .csv calibration file also didn't make it into the distribution, so we will continue to distribute that via github releases until that's fixed.
