### ISSUE TITLE
Remove separate arm64 installation documentation

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#314]
In `recOrder` 0.2.x a x86_64 Python environment is required for napari/PyQt5 to work on macOS. With #313 we can remove those instructions in the next release since the same installation process now works for both x86_64 and arm64 machines.

**Comment by talonchandler** [comment]
Cannot be closed before 0.3.0 PyPI release, so I'm removing this from the milestone and tagging @ziw-liu to complete it after release.
