### ISSUE TITLE
Installation isn't working on (intel?) macs?

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#321]
@ziw-liu in a new conda environment:
```
pip install recOrder-napari
napari -w recOrder-napari
```
results in:
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/recorder-pip-test/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/recorder-pip-test/lib/python3.9/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/opt/anaconda3/envs/recorder-pip-test/lib/python3.9/site-packages/napari/__main__.py", line 314, in _run
    ) or plugin_manager.get_widget(pname)
  File "/opt/anaconda3/envs/recorder-pip-test/lib/python3.9/site-packages/napari/plugins/_plugin_manager.py", line 610, in get_widget
    raise KeyError(msg)
KeyError: "Plugin 'recOrder-napari' does not provide any dock widgets"
```
and `recOrder-napari` doesn't appear in the plugin menu. 

As expected, `recOrder-napari==0.2.1` is installed and `import recOrder` works. Interestingly, I get the same result when I install `recOrder-napari==0.2.0`.

**Comment by talonchandler** [comment]
Just tried to install from the main branch and received the same error: `pip install -e .`. So it's not just a PyPI problem...

**Comment by talonchandler** [comment]
`recOrder-napari` appears as "installed" without a checkbox...but it doesn't appear in the plugin dropdown menu...

<img width="1053" alt="Screen Shot 2023-02-17 at 3 24 30 PM" src="https://user-images.githubusercontent.com/9554101/219815778-822a3a3d-68a4-4db2-8a0c-ba834f2545ce.png">

**Comment by talonchandler** [comment]
@ziw-liu couldn't reproduce on his mac, but we reproduced together on mine. I'm using this conda-installed python: 

`pkgs/main/osx-64::python-3.9.16-h218abb5_0`

**Comment by ziw-liu** [comment]
Tried on Linux (x64) and Windows (x64) too and could not reproduce.

**Comment by talonchandler** [comment]
@ziw-liu were you able to run it with the same python I used? Do you suspect this to be an intel-specific issue?

**Comment by ziw-liu** [comment]
> were you able to run it with the same python I used? Do you suspect this to be an intel-specific issue?

I used Python 3.9.16 for all 3 tests. I believe I was translating x64 Python via Rosetta on macOS (M1) since 0.2.1 does not have the Qt6 fix for pip, and native x64 on Linux (AMD) and Windows (Intel).

**Comment by talonchandler** [comment]
At @ziw-liu's suggestion: I ran `napari --reset` then retried and everything is working again. I lost old napari settings to help me test which setting caused this issue, but I'll keep my eyes open. 

Thanks @ziw-liu!
