### ISSUE TITLE
`recOrder` (and `waveorder`) should use `float32` by default

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#324]
Our raw `uint16` data doesn't benefit from our current `float64`s, and we'll benefit from increased throughput, especially in our ffts.

**Comment by talonchandler** [comment]
This will require significant work on `waveorder` and `recOrder`...assigning to 1.0.0.

**Comment by ziw-liu** [comment]
Is this fixed with waveorder v2.0.0rc3?

**Comment by talonchandler** [comment]
Yep! Just confirmed that this is now fixed.
