### ISSUE TITLE
Stale branch

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#330]
The [`hardware_sequencing`](https://github.com/mehta-lab/recOrder/tree/hardware_sequencing) branch is stale (660 commits behind). @mattersoflight Is the only commit https://github.com/mehta-lab/recOrder/commit/ed93d1abd038e0119de0df12abd94dc8187e19ef still useful?

**Comment by mattersoflight** [comment]
The branch is useful, but the code is likely stale. The goal was to version the code we use to verify the accuracy of hardware sequencing-based calibration.  I pulled the code from sandbox and versioned here. 

These scripts have likely been improved by @edyoshikun , @talonchandler , or @ieivanov. 

I'll let them chime in.

**Comment by ieivanov** [comment]
This commit seems to be `.py` versions of the code in here: https://github.com/czbiohub/compmicro-sandbox/tree/master/recOrder/LC_eval. @mattersoflight, it looks like you converted the Jupyter Notebooks to python scripts before uploading them here? I think it's safe to delete this branch from the recOrder repo and keep the code in compmicro-sandbox (or wherever we keep prototyping code, I'm still catching up on that discussion).

**Comment by mattersoflight** [comment]
Deleting the branch and closing this issue.
