### ISSUE TITLE
Need to update the zenodo zarr files for 0.4.0

### ISSUE THREAD

**Issue by edyoshikun** [mehta-lab/recOrder#361]
Currently our zendo `recOrder_test_data` for the `.zarr` still uses the old zarr structure, which is incompatible with the 0.4 ome-zarr specs implemented by iohub. For testing the new 0.4.0dev branch one needs to use the latest iohub dev and `convert()` the datasets. Will that be the expected behavior?  @ziw-liu @talonchandler 

https://zenodo.org/record/6983916/files/recOrder_test_data.zip?download=1

**Comment by talonchandler** [comment]
Thanks @edyoshikun good call. I can fix this.

**Comment by ziw-liu** [comment]
If we want to do 0.4.0 testing, does these also need the new calibration metadata, BG, and the reconstruction config files? If so it may be easier to just acquire some new images...

**Comment by talonchandler** [comment]
I have a test dataset, but I'll wait for #370 before uploading.

**Comment by talonchandler** [comment]
```
2023_08_17_polarization_spokes/

├── polarization_calibration.txt
│   ├── background.zarr
│   ├── polarization_calibration.txt
│   ├── reconstruction.zarr
│   ├── reconstruction_settings.yml
│   └── transfer_function.zarr
├── birefringence_snap_0
│   ├── raw_data.zarr
│   ├── reconstruction.zarr
│   ├── reconstruction_settings.yml
│   └── transfer_function.zarr
├── phase_snap_0
│   ├── raw_data.zarr
│   │   └── 0
│   │       └── 0
│   ├── reconstruction.zarr
│   │   └── 0
│   │       └── 0
│   ├── reconstruction_settings.yml
│   └── transfer_function.zarr
├── birefringence_and_phase_snap_0
│   ├── raw_data.zarr
│   ├── reconstruction.zarr
│   ├── reconstruction_settings.yml
│   └── transfer_function.zarr

|
├── mda_brightfield.zarr
│   ├── A
│   │   └── 1
│   │       └── 0
│   └── B
│       └── 2
│           ├── 0
│           └── 1
├── mda_polarization.zarr
│   ├── A
│   │   └── 1
│   │       └── 0
│   └── B
│       └── 2
│           ├── 0
│           └── 1

```
