### ISSUE TITLE
Add sample data contribution

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/recOrder#370]
@andy-sweet pointed out that a [sample data plugin contribution](https://napari.org/stable/plugins/contributions.html#contributions-sample-data) is very helpful for developers.

This also seems to be an easy way to distribute some of our sample datasets directly with the plugin installation.

Related: #361

**Comment by ziw-liu** [comment]
In addition to URIs of real data, we can also potentially register the fantoms with the [sample data function schema](https://napari.org/stable/plugins/guides.html#sample-data-example).

**Comment by andy-sweet** [comment]
If there are sample data that lend themselves to the vector field visualizations we discussed (e.g. mapping to a scalar image, color encodings, tensor glyph instances) that would be particularly exciting based on my past life working in diffusion MRI and some potential upcoming work in napari around color/style encodings.

**Comment by talonchandler** [comment]
We decided to add a Kazansky target acquisition and reconstruction as a sample data contribution for 0.4.0. 

Later, we will consider adding biological sample data.

**Comment by talonchandler** [comment]
I have acquired a dataset that I will upload to zenodo and provide as a sample data contribution when we complete #421.
