### ISSUE TITLE
napari hub preview tests are failing

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#387]
The napari hub preview is failing in CI/CD. We'll need to fix this ahead of the 0.4.0 release. 

Example of a failing run:
https://github.com/mehta-lab/recOrder/actions/runs/5662596981/job/15342834387#step:15:862

**Comment by ziw-liu** [comment]
Submitted https://github.com/chanzuckerberg/napari-hub-preview-action/issues/10.

**Comment by ziw-liu** [comment]
> Submitted [chanzuckerberg/napari-hub-preview-action#10](https://github.com/chanzuckerberg/napari-hub-preview-action/issues/10).

Confirmed to be an upstream bug and a fix is underway.

**Comment by talonchandler** [comment]
Fixed upstream
