### ISSUE TITLE
check that necessary parameters for acquisition and analysis are supplied before acquiring data

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#39]
I missed to set the parameters needed for phase reconstruction before starting the acquisition. I received following error *after* the acquisition was completed and before the data was analyzed:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2934183/149235299-85c7136e-93fe-4120-83aa-644d0b9abcbb.png">

Is there a module that checks whether necessary parameters are provided before the acquisition starts?

**Comment by camFoltz** [comment]
There is not a specific module, but there is similar code elsewhere that's easily adapted for this.  I agree that this will be a good check to implement before moving on with the acquisition.

**Comment by camFoltz** [comment]
implemented in #31
