### ISSUE TITLE
[BUG] Dragging HCS plates into ome-zarr does not generate overlay 

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#416]
The latest versions of `recOrder` fail to generate birefringence overlays when you drag and drop an HCS plate. 

For now, a workaround is to drag in individual positions. 

Thanks @ziw-liu for the debugging session and for handling the fix.

**Comment by ziw-liu** [comment]
Filed https://github.com/ome/ome-zarr-py/issues/297.
