### ISSUE TITLE
[BUG] GUI-generated layers are incorrectly scaled

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#418]
`iohub convert` and `recorder reconstruct` now pass scale metadata smoothly through their pipelines. 

This introduces a "good" bug: if you drag in a previously acquired zarr store it will be correctly scaled, but the GUI-generated layers are not correctly scaled.

I will add correct scale information for all of the `add_image` functions in `recOrder` to fix this.

**Comment by edyoshikun** [comment]
I saw this bug too, by this you mean you will do something along these lines right?

```python
voxel_size = position.scale
viewer.add_image(image_array, scale=(1,1)+voxel_size)
```

**Comment by talonchandler** [comment]
@edyoshikun see discussion in #419.

The solution will be roughly what you wrote, though there are some subtle edge case when we generate birefringence overlays.
