### ISSUE TITLE
[BUG] iohub version incompatibility with recorder-napari 0.4.1

### ISSUE THREAD

**Issue by aaronalvarezcz** [mehta-lab/recOrder#466]
There is a dependency conflict when installing the recOrder package. The current version of recorder-napari (0.4.1) requires iohub==0.1.0.dev5, but the available version of iohub is 0.1.0.

**Comment by talonchandler** [comment]
Hey @aaronalvarezcz, can you expand on the issue you're seeing here? 

I just tried a local from-scratch installation and didn't run into any dependency conflicts. `iohub==0.1.0dev5` seems to still be available from PyPI (I check with `pip install --no-cache-dir recOrder-napari` to make sure I wasn't using a cache).

**Comment by aaronalvarezcz** [comment]
sure, when doing `pip install recOrder-napari` it requires `iohub==0.1.0.dev5`, which is missing some functionality (i found out because i couldn't use the `--chunks` flag with `iohub convert`. I had to reinstall iohub to get version 0.1.0.
