### ISSUE TITLE
[BUG] Registered data issue A549 cells

### ISSUE THREAD

**Issue by alishbaimran** [mehta-lab/recOrder#472]
**Summary and expected behavior**

I'm getting a white square (values seem to be 1 when I hover over the square in napari) showing up in napari when I try to visualize data for some fovs and specific cells/patches. It seems that the bug is coming from my registered.zarr. The path to the registered file is: `/hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/2-register/registered.zarr`. 

![image](https://github.com/mehta-lab/recOrder/assets/44557946/37069332-f3e5-46d9-88ba-ff0192d34f00)

The specific cells I see the issue in is A/3/0 6th timestep and 36th z slice. channel 1 is rfp and channel 3 is phase. These are the channels we are looking at. 

The patches data can be found at: `/hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/6-patches/patch_final_2.zarr`. The specific cells I am getting the issue with are at `/hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/6-patches/patch_final_2.zarr/A/3/fov0cell10` and` /hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/6-patches/patch_final_2.zarr/A/3/fov0cell11` around timestep 5/6th and 36th z slice. 

I've plotted the following histograms from the patches ome_zarr for A/3/fov0cell11 at timestep 6, z slice 36. Channel 0 is rfp and channel 1 on the diagram is phase. 
![image](https://github.com/mehta-lab/recOrder/assets/44557946/d7931e09-c2e4-427b-89d9-1d7a1ea17df9)
![image](https://github.com/mehta-lab/recOrder/assets/44557946/a1c4bed9-31a4-4431-bc65-944f3fe253e9)

This is the registered file data from A/3/0 at timestep 6, z slice 36. Channel 1 is rfp and channel 3 on the diagram is phase. 
![image](https://github.com/mehta-lab/recOrder/assets/44557946/b4d8079f-af6a-418f-94ae-01e854df3df7)
![image](https://github.com/mehta-lab/recOrder/assets/44557946/4051623a-f7da-4b64-b25d-349640454842)

**Comment by mattersoflight** [comment]
@Soorya19Pradeep looks like the fluorescence channel in registerd.zarr has zeros (this can be due to noise) and the phase channel has few saturated pixels. Please look into this and figure out why we are getting clipped pixel values in the registration process. 

@alishbaimran this does not block the current iteration on model and dataloader.

**Comment by talonchandler** [comment]
@Soorya19Pradeep has narrowed this bug to SLURM-parallelized registration steps, so this issue might belong to shrimpy. 

@edyoshikun also checked that the incorrect patches do not correspond to the chunk sizes. 

We checked the memory usage of @ziw-liu's job to make sure that there wasn't an OOM or other resource issue...no problem there...RAM usage was ~10%. 

My mind goes to SLURM and ants registration issues? Not really sure yet...

**Comment by ziw-liu** [comment]
@alishbaimran it seems like you accidentally overwrote the source data when creating the patches. Note that these patches follow your first version's size (64 px) and move with the cells. By default, iohub opens the zarr store in a read-only mode (4th code block of [this example](https://czbiohub-sf.github.io/iohub/main/auto_examples/run_single_fov_ome_zarr.html)). Please check your script to remove the unnecessary file mode argument that allows writing. Also refer to [API documentation](https://czbiohub-sf.github.io/iohub/main/api/ngff.html#iohub.open_ome_zarr).

```sh
/hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/2-register/registered.zarr/A/3/0/0/5 stat 0/0/0/0
  File: 0/0/0/0
  Size: 257227143       Blocks: 502408     IO Block: 4194304 regular file
Device: f87a3582h/4168758658d   Inode: 162130443615912125  Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 5712/alishba.imran)   Gid: (25022/group.tlg.icd)
Access: 2024-07-03 09:01:09.000000000 -0700
Modify: 2024-06-20 16:53:28.000000000 -0700
Change: 2024-06-20 16:53:28.000000000 -0700
 Birth: 2024-06-20 16:53:27.000000000 -0700
/hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/2-register/registered.zarr/A/3/0/0/5 la 0/0/0/0
-rw-rw-r-- 1 alishba.imran group.tlg.icd 246M Jun 20 16:53 0/0/0/0
```

**Comment by Soorya19Pradeep** [comment]
Just to clarify, I was getting inappropriate results using slurm as I was not allocating enough resources. Thanks @ziw-liu for figuring it out!

**Comment by talonchandler** [comment]
Team effort! 

@alishbaimran, can you close this issue when you've checked that it's solved.

**Comment by alishbaimran** [comment]
> @alishbaimran it seems like you accidentally overwrote the source data when creating the patches. Note that these patches follow your first version's size (64 px) and move with the cells. By default, iohub opens the zarr store in a read-only mode (4th code block of [this example](https://czbiohub-sf.github.io/iohub/main/auto_examples/run_single_fov_ome_zarr.html)). Please check your script to remove the unnecessary file mode argument that allows writing. Also refer to [API documentation](https://czbiohub-sf.github.io/iohub/main/api/ngff.html#iohub.open_ome_zarr).
> 
> ```shell
> /hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/2-register/registered.zarr/A/3/0/0/5 stat 0/0/0/0
>   File: 0/0/0/0
>   Size: 257227143       Blocks: 502408     IO Block: 4194304 regular file
> Device: f87a3582h/4168758658d   Inode: 162130443615912125  Links: 1
> Access: (0664/-rw-rw-r--)  Uid: ( 5712/alishba.imran)   Gid: (25022/group.tlg.icd)
> Access: 2024-07-03 09:01:09.000000000 -0700
> Modify: 2024-06-20 16:53:28.000000000 -0700
> Change: 2024-06-20 16:53:28.000000000 -0700
>  Birth: 2024-06-20 16:53:27.000000000 -0700
> /hpc/projects/intracellular_dashboard/viral-sensor/2024_02_04_A549_DENV_ZIKV_timelapse/2-register/registered.zarr/A/3/0/0/5 la 0/0/0/0
> -rw-rw-r-- 1 alishba.imran group.tlg.icd 246M Jun 20 16:53 0/0/0/0
> ```

Yes I think I accidentally overwrote data which impacted some cells in one FOV before I stopped the script. Is there a way to recover the original registered file?
