### ISSUE TITLE
Disable mouse scrolling on drop-down menus

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#48]
Is it possible to disable mouse scrolling on drop-down menus? Sometimes I change parameter values by scrolling over the drop-down field when I actually intend to scroll up or down the Calibration plugin. Is it possible to change drop-down field by mouse click only?

**Comment by camFoltz** [comment]
I believe this is fixed in #31, I changed the focus policy of all of the combo boxes.  I will need to test it out on a windows system though because I have only seen this issue before on Windows.

**Comment by camFoltz** [comment]
Still not fixed, this behavior is only on windows machines I will have to investigate further

**Comment by camFoltz** [comment]
fixed and tested on windows in #31.  Overwrote wheelEvent for all combo boxes to do nothing
