### ISSUE TITLE
recOrder birefringence snaps don't save raw intensity images

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#53]
Raw intensity images should be saved in the zarr store, in case we decide to process the data differently at a later point

**Comment by camFoltz** [comment]
So my initial thought here is to just keep the files that are written to disk in the first place by micromanager (tiff files).  The user can then use the zarr converter if they want it to be in the zarr format OR we can go ahead and convert it to zarr and then delete the tiff files.

I am against placing the raw data inside the same ome-zarr store as the processed data is that it would be weird to process later (and incompatible with our recOrder processing pipeline).

**Comment by camFoltz** [comment]
in recent commit to #31, I have made it such that the tiff data captured by the snap is output to zarr via the `converter`.  This will allow the user to go back and reconstruct the raw snaps with different parameters if they so desire.
