### ISSUE TITLE
test and refine calibration assessment

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#55]
This issue is to document the calibration assessment that the plugin provides, and refine those assessments.
-------

## 2022/01/27
Extinction was poor, because condenser was not adjusted for Kolher illumination, but the plugin suggested turning the polarizer. 

Before Kohler
![image](https://user-images.githubusercontent.com/2934183/151445161-41f10537-5cf7-4965-8c43-658ec0b55558.png)

After Kholer
![image](https://user-images.githubusercontent.com/2934183/151445659-40284e3f-9555-4391-82a3-1d0b20f25445.png)

Update above status message to say, "Poor extinction. Possibilities are: a) polarizer and LC are not oriented properly, b) circular analyzer has wrong handedness, c) the condenser is not setup for Kohler illumination, d) a component, such as autofocus dichroic, distorts the polarization state."

**Comment by camFoltz** [comment]
Thanks for bringing this up.  I agree that we need to be more general in the assessments.

 I would also like to discuss what may be the best bounds for certain error messages.  Here is the current implementation:

```
0.2 < LC-A < 0.4
0.4 < LC-B < 0.75
extinction >= 100
--------------------> Assess: Successful Calibration

0.2 < LC-A < 0.4
0.4 < LC-B < 0.75
80 <= extinction <= 100
--------------------> Assess: Successful Calibration, Okay Extinction Ratio

0.2 < LC-A < 0.4
0.4 < LC-B < 0.75
extinction < 90
--------------------> Assess: Poor Extinction try tunning "..."

0.2 < LC-A < 0.4
 LC-B < 0.4 or LCB > 0.75
--------------------> Assess: Calibration Failed, wrong handedness of analyzer or linear polarizer 90 degrees off

LC-A < 0.2 or LCA-A > 0.4
--------------------> Assess: Calibration Failed, unknown origin of issue
```

Right now these values are quite arbitrary (the value of 80 for the extinction ratio for instance) and as @ieivanov mentioned in the lab meeting, if the calibration curves are off then the calibration could be successful but the values could still hit outside of this range.

**Comment by camFoltz** [comment]
This has been simplified in #31 to just use the extinction ratio and not any LC-values to assess the calibration. Gives ideas to the user on how to fix the problem if calibration is poor.
