### ISSUE TITLE
Create Issue Template for new issues

### ISSUE THREAD

**Issue by camFoltz** [mehta-lab/recOrder#72]
We should standardize how users submit an issue similar to pycromanager https://github.com/micro-manager/pycro-manager/issues.  This allows for easier tracking of bugs and bug fixes

**Comment by camFoltz** [comment]
Note this needs to be done by an admin of the repo.

**Comment by camFoltz** [comment]
@mattersoflight I recommend following pycromanager's issue templates:

[https://github.com/micro-manager/pycro-manager/tree/main/.github/ISSUE_TEMPLATE](https://github.com/micro-manager/pycro-manager/tree/main/.github/ISSUE_TEMPLATE)

**Comment by mattersoflight** [comment]
@camFoltz  - thanks for the link. I've updated the issue templates and also included one template for documentation.
