### ISSUE TITLE
Package name for PyPi

### ISSUE THREAD

**Issue by camFoltz** [mehta-lab/recOrder#78]
Unfortunately` recorder is taken on pypi for a python package name.  We will have to consider other deployment names for recOrder.

We could in theory do something like `napari-recOrder` to follow other napari plugins or something similar.  I am not entirely sure what would be best here.  @mattersoflight

**Comment by mattersoflight** [comment]
`recOrder-napari` or `record-order` are good alternatives. I prefer the first one. 
Related question, was the plugin initiated with coockiecutter plugin, [such that](https://github.com/napari/cookiecutter-napari-plugin#set-up-automatic-deployments) it can be discovered by napari and napari hub?

**Comment by camFoltz** [comment]
I like the first option as well.  The plugin has the proper flags to be discoverable by pypi as soon as it is released there (no matter what name we choose).

**Comment by camFoltz** [comment]
Let it be noted that there are some bugs when changing the name of the repository as Shalin and I discovered a few weeks ago.

It seems that changing the name within the setup.py file causes napari to no longer install or recognize the repo as a plugin.  Even when changing the napari.yml file to match the new name the bug still occurs.  Perhaps we can change the setup.py file and then use the command `npe2 convert`

**Comment by mattersoflight** [comment]
@camFoltz  I recall you converting the plugin to npe2 format on the `calibration_plugin` branch in the context of registering the plugin with the menu. I've merged the branch with main. I will look into npe2 compliance next Tuesday, let me know if you figure out the status.

**Comment by camFoltz** [comment]
@mattersoflight Yes, I did in fact do this.  I am wondering if it is worth trying the conversion again after changing the setup.py file.  I am suggesting this because I was unable to manually edit the npe2 required napari.yaml files to have it be recognized as a plugin.  Hopefully the npe2 convert after the name change will fix this.
