### ISSUE TITLE
Processing older data sets + additional suggestions

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/recOrder#86]
Issues and suggestions based on my experience as a new user of recorder:

1. The new version of recorder do not support the processing of single sheet tiff files (format in which older datasets are acquired and stored). The images from the older data sets cannot be reconstructed as they lack calibration data text files. The inclusion of swing parameter on the recorder reconstruction interface might be useful. 

2. The names 'Global' and 'local' background correction in the background reconstruction section of recorder are counterintuitive. The names 'measured' background for corrections using background images, and 'estimated' background for fitted background is more intuitive.

3. Reconstructed background and sample images can be displayed in hsv colormap as default as it is more intuitive than grayscale colormaps.

**Comment by talonchandler** [comment]
Hi Soorya!

I have a few followup/clarification questions (I'm building up my knowledge base here too) but many of my comments lean on @mattersoflight:

>> The new version of recorder do not support the processing of single sheet tiff files (format in which older datasets are acquired and stored)

Have you been trying to process these datasets via the CLI or the napari plugin? My impression is Johanna's current workflow is to use `recOrder.convert` to convert these files to zarr then view/process them. Have you tried this?

@mattersoflight do we have plans/goals to process or convert single sheet tiffs. 

>> The inclusion of swing parameter on the recorder reconstruction interface might be useful.

Are you looking to see the swing parameter that the data was collected with from the reconstruction interface? I think I like this idea, but I'm wondering if this leads to showing all of the metadata. Maybe this is what we want?

>> The names 'Global' and 'local' background correction in the background reconstruction section of recorder are counterintuitive. The names 'measured' background for corrections using background images, and 'estimated' background for fitted background is more intuitive. 

Makes sense to me!

>> Reconstructed background and sample images can be displayed in hsv colormap as default as it is more intuitive than grayscale colormaps.

I like it too!

**Comment by talonchandler** [comment]
Soorya and I just spoke about analyzing old data that may not have swing metadata available. I'm a bit confused about this use case: is the swing metadata lost for a large fraction of old data that needs to be analyzed? 

Do this mean we need the ability to (re)analyze all data with a user-selected swing value?

Thanks!

**Comment by talonchandler** [comment]
@mattersoflight and I just spoke and concluded that in the case where old data needs to be reanalyzed with a different/new swing value we can generate a config file "by hand" (likely by modifying an example). 

Re: the other issues...I'll leave them open and address them later. 

Thanks Soorya and Shalin.

**Comment by talonchandler** [comment]
Closing to split into #134, #136, #137.
